// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9HpsAjYgqPLvPWTxt-WXmiNwuIvjayKs',
    appId: '1:781521159682:web:039fd4b44792b3f4a2c91b',
    messagingSenderId: '781521159682',
    projectId: 'potencia-e55e5',
    authDomain: 'potencia-e55e5.firebaseapp.com',
    databaseURL: 'https://potencia-e55e5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'potencia-e55e5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHE5FaZkN3ptVAONtfYOA3mzdJAapTsn4',
    appId: '1:781521159682:android:c5703196ecf618bba2c91b',
    messagingSenderId: '781521159682',
    projectId: 'potencia-e55e5',
    databaseURL: 'https://potencia-e55e5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'potencia-e55e5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWa1inxX3KSbAvzA8pAisNagoSw7unDp8',
    appId: '1:781521159682:ios:dd10a756d359fe61a2c91b',
    messagingSenderId: '781521159682',
    projectId: 'potencia-e55e5',
    databaseURL: 'https://potencia-e55e5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'potencia-e55e5.appspot.com',
    iosClientId: '781521159682-bedadb5fjm7ldrn8098tvmhnf1gp6avf.apps.googleusercontent.com',
    iosBundleId: 'com.example.potencia',
  );
}
